[package]
name = "aoc"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0/MIT"

[dependencies]
aoc-derive = { path = "../aoc-derive" }
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive"] }
color-eyre = "0.6.5"
eyre = "0.6.14"
mktemp = "0.5.1"
thiserror = "2.0.20"

[dev-dependencies]
insta = "1.48.0"
serial_test = { version = "4.0.1", default-features = false }
