[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"

[dependencies]
aoc-derive = { path = "../aoc-derive" }
chrono = "0.4.31"
clap = { version = "4.4.5", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.8"
itertools = "0.11.0"
lazy_static = "1.4.0"
mktemp = "0.5.1"
thiserror = "1.0.49"

[dev-dependencies]
insta = "1.33.0"
serial_test = { version = "2.0.0", default-features = false }
