[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
aoc-derive = { path = "../aoc-derive" }
chrono = "0.4.22"
clap = { version = "4.0.15", features = ["derive"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
