[package]
name = "aoc-build"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
prettyplease = "0.1.25"
regex = "1.9.5"
syn = "1.0.109"
