[package]
name = "dummy-year"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0/MIT"

[dependencies]
aoc = { path = "../aoc" }
bytecount = "0.6.8"
eyre = "0.6.12"

[build-dependencies]
aoc-build = { path = "../aoc-build" }

[features]
