[package]
name = "aoc-derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc_derive"
proc_macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = { version = "1.0.102", features = ["full", "parsing"] }

[dev-dependencies]
trybuild = "1.0.71"
